---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-csi-vault-sa
  namespace: tenant
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-tenant-sa-script
data:
  add-tenant-sa.sh: |
    # login into vault to add a configuration for the tenant
    vault login ${VAULT_DEV_ROOT_TOKEN_ID}

    # create a secret store for the tenant
    vault secrets enable -path="${TENANT_NAMESPACE}" kv

    # create a policy for the tenant
    vault policy write "${TENANT_NAMESPACE}" - << EOS
    path "tenant/*" {
      capabilities = ["create", "update", "delete", "read", "list"]
    }

    path "sys/mounts" {
      capabilities = ["read"]
    }
    EOS

    # allow access with the tenant ServiceAccount
    vault write "auth/${CLUSTER_IDENTIFIER}/role/${PLUGIN_ROLE}" \
        bound_service_account_names="${TENANT_SA_NAME}" \
        bound_service_account_namespaces="${TENANT_NAMESPACE}" \
        policies="${TENANT_NAMESPACE}"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: vault-tenant-sa
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: vault-tenant-sa
    spec:
      serviceAccountName: rbd-csi-vault-token-review
      volumes:
        - name: vault-tenant-sa-script
          configMap:
            name: vault-tenant-sa-script
      containers:
        - name: vault-tenant-sa-job
          image: docker.io/library/vault:latest
          volumeMounts:
            - mountPath: /scripts
              name: vault-tenant-sa-script
          env:
            - name: HOME
              value: /tmp
            - name: CLUSTER_IDENTIFIER
              value: kubernetes
            - name: SERVICE_ACCOUNT_TOKEN_PATH
              value: /var/run/secrets/kubernetes.io/serviceaccount
            - name: K8S_HOST
              value: https://kubernetes.default.svc.cluster.local
            - name: PLUGIN_ROLE
              value: csi-kubernetes
            - name: TENANT_SA_NAME
              value: ceph-csi-vault-sa
            - name: TENANT_NAMESPACE
              value: tenant
            - name: VAULT_ADDR
              value: http://vault.default.svc.cluster.local:8200/
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: sample_root_token_id
          command:
            - /bin/sh
            - /scripts/add-tenant-sa.sh
          imagePullPolicy: "IfNotPresent"
      restartPolicy: Never
