apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: openshift-storage.nfs.csi.ceph.com
spec:
  attachRequired: false
  fsGroupPolicy: File
  podInfoOnMount: false
  requiresRepublish: false
  storageCapacity: false
  volumeLifecycleModes:
  - Persistent
