---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-cephcsi-cephfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-nfs
