---
name: multi-arch-build
# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - '*'
permissions:
  contents: read

jobs:
  codespell:
    name: multi-arch-build
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      # multi-arch-build has been removed in the release-4.19 branch, the test
      # container-image with pre-upstream patches is single-arch only.
      - name: single-arch-build
        run: make containerized-build
